### ISSUE TITLE
low accuracy

### ISSUE THREAD

**Issue by kk19990709** [jlealtru/website_tutorials#1]
By using_Longformer_with_IMDB, I changed the code `per_device_train_batch_size=4,
gradient_accumulation_steps=4,`
and I got 86.944% as accuracy but not 93.4% or 95.7%
would you like to give some help?

**Comment by jlealtru** [comment]
The gradient is not updating properly, I would try changing `gradient_accumulation_steps` to 8 (as suggested in the original paper) or even to 16. What learning rate did you use?
